
SkadaDB = {
	["namespaces"] = {
		["LibDualSpec-1.0"] = {
		},
	},
	["profileKeys"] = {
		["猫乄 - 阿尔萨斯"] = "Default",
		["秋心 - 阿尔萨斯"] = "Default",
		["木叶之说 - 阿尔萨斯"] = "Default",
		["你见过我吗 - 阿尔萨斯"] = "Default",
		["阿服第一武僧 - 阿尔萨斯"] = "Default",
		["霜天晓角 - 阿尔萨斯"] = "Default",
		["丨术丨 - 阿尔萨斯"] = "Default",
		["老弓 - 阿尔萨斯"] = "Default",
		["悦战 - 阿尔萨斯"] = "Default",
		["冰火兮 - 阿尔萨斯"] = "Default",
		["古剑 - 阿尔萨斯"] = "Default",
		["作业还没写 - 阿尔萨斯"] = "Default",
	},
	["profiles"] = {
		["Default"] = {
			["windows"] = {
				{
					["set"] = "total",
					["y"] = -136.998291015625,
					["name"] = "1",
					["point"] = "TOPLEFT",
					["mode"] = "伤害",
					["barwidth"] = 314.0190124511719,
					["background"] = {
						["color"] = {
							["a"] = 0.400000035762787,
						},
						["height"] = 115.0022201538086,
						["texture"] = "None",
					},
					["x"] = 1.999958992004395,
				}, -- [1]
				{
					["titleset"] = true,
					["barheight"] = 18,
					["color"] = {
						["a"] = 0.6,
						["r"] = 0.3,
						["g"] = 0.3,
						["b"] = 0.3,
					},
					["issolidbackdrop"] = false,
					["classicons"] = true,
					["barslocked"] = false,
					["useframe"] = true,
					["clickthrough"] = false,
					["wipemode"] = "",
					["set"] = "current",
					["hidden"] = false,
					["y"] = 205.5008544921875,
					["barfont"] = "Accidental Presidency",
					["name"] = "111",
					["display"] = "bar",
					["x"] = 3.000073194503784,
					["barfontflags"] = "",
					["isusingelvuiskin"] = true,
					["point"] = "LEFT",
					["strata"] = "LOW",
					["classcolortext"] = false,
					["spellschoolcolors"] = true,
					["barbgcolor"] = {
						["a"] = 0.6,
						["r"] = 0.3,
						["g"] = 0.3,
						["b"] = 0.3,
					},
					["barcolor"] = {
						["a"] = 1,
						["r"] = 0.3,
						["g"] = 0.3,
						["b"] = 0.8,
					},
					["showself"] = true,
					["returnaftercombat"] = false,
					["title"] = {
						["textcolor"] = {
							["a"] = 1,
							["r"] = 0.9,
							["g"] = 0.9,
							["b"] = 0.9,
						},
						["color"] = {
							["a"] = 1,
							["r"] = 0.3,
							["g"] = 0.3,
							["b"] = 0.3,
						},
						["bordercolor"] = {
							["a"] = 1,
							["r"] = 0,
							["g"] = 0,
							["b"] = 0,
						},
						["font"] = "Accidental Presidency",
						["fontsize"] = 13,
						["height"] = 20,
						["fontflags"] = "",
						["bordertexture"] = "None",
						["borderthickness"] = 2,
						["texture"] = "Armory",
					},
					["version"] = 1,
					["isonnewline"] = false,
					["roleicons"] = false,
					["barorientation"] = 1,
					["mode"] = "伤害",
					["scale"] = 1,
					["fixedbarwidth"] = false,
					["width"] = 600,
					["textcolor"] = {
						["r"] = 0.9,
						["g"] = 0.9,
						["b"] = 0.9,
					},
					["buttons"] = {
						["segment"] = true,
						["menu"] = true,
						["mode"] = true,
						["report"] = true,
						["reset"] = true,
					},
					["bartexture"] = "BantoBar",
					["barwidth"] = 314.0337219238281,
					["barspacing"] = 0,
					["modeincombat"] = "",
					["smoothing"] = false,
					["reversegrowth"] = false,
					["enabletitle"] = true,
					["snapto"] = true,
					["classcolorbars"] = true,
					["isusingclasscolors"] = true,
					["barfontsize"] = 13,
					["background"] = {
						["height"] = 112.9985198974609,
						["bordercolor"] = {
							["a"] = 1,
							["r"] = 0,
							["g"] = 0,
							["b"] = 0,
						},
						["borderthickness"] = 1,
						["tile"] = false,
						["color"] = {
							["a"] = 0.4,
							["r"] = 0,
							["g"] = 0,
							["b"] = 0,
						},
						["bordertexture"] = "Blizzard Party",
						["tilesize"] = 0,
						["texture"] = "None",
					},
					["height"] = 30,
				}, -- [2]
				{
					["titleset"] = true,
					["barheight"] = 18,
					["color"] = {
						["a"] = 0.6,
						["b"] = 0.3,
						["g"] = 0.3,
						["r"] = 0.3,
					},
					["issolidbackdrop"] = false,
					["classicons"] = false,
					["barslocked"] = false,
					["useframe"] = true,
					["clickthrough"] = false,
					["wipemode"] = "",
					["set"] = "total",
					["hidden"] = false,
					["y"] = -44.0001220703125,
					["barfont"] = "EUI",
					["name"] = "治疗",
					["version"] = 1,
					["display"] = "bar",
					["height"] = 30,
					["barfontflags"] = "",
					["isusingelvuiskin"] = true,
					["title"] = {
						["textcolor"] = {
							["a"] = 1,
							["b"] = 0.9,
							["g"] = 0.9,
							["r"] = 0.9,
						},
						["color"] = {
							["a"] = 1,
							["b"] = 0.3,
							["g"] = 0.3,
							["r"] = 0.3,
						},
						["bordercolor"] = {
							["a"] = 1,
							["b"] = 0,
							["g"] = 0,
							["r"] = 0,
						},
						["font"] = "EUI",
						["fontsize"] = 13,
						["fontflags"] = "",
						["height"] = 20,
						["borderthickness"] = 2,
						["bordertexture"] = "None",
						["texture"] = "Armory",
					},
					["strata"] = "LOW",
					["point"] = "TOPLEFT",
					["spellschoolcolors"] = true,
					["barbgcolor"] = {
						["a"] = 0.6,
						["b"] = 0.3,
						["g"] = 0.3,
						["r"] = 0.3,
					},
					["barcolor"] = {
						["a"] = 1,
						["b"] = 0.8,
						["g"] = 0.3,
						["r"] = 0.3,
					},
					["isonnewline"] = false,
					["barfontsize"] = 13,
					["enabletitle"] = true,
					["returnaftercombat"] = false,
					["snapto"] = true,
					["roleicons"] = false,
					["barorientation"] = 1,
					["mode"] = "治疗",
					["reversegrowth"] = false,
					["width"] = 600,
					["fixedbarwidth"] = false,
					["textcolor"] = {
						["b"] = 0.9,
						["g"] = 0.9,
						["r"] = 0.9,
					},
					["barspacing"] = 0,
					["buttons"] = {
						["segment"] = true,
						["menu"] = true,
						["mode"] = true,
						["report"] = true,
						["reset"] = true,
					},
					["barwidth"] = 318.0036315917969,
					["specicons"] = true,
					["bartexture"] = "BantoBar",
					["smoothing"] = false,
					["scale"] = 1,
					["background"] = {
						["color"] = {
							["a"] = 0.4,
							["b"] = 0,
							["g"] = 0,
							["r"] = 0,
						},
						["bordertexture"] = "ElvUI GlowBorder",
						["borderthickness"] = 2,
						["tile"] = false,
						["height"] = 66.99955749511719,
						["bordercolor"] = {
							["a"] = 1,
							["b"] = 0,
							["g"] = 0,
							["r"] = 0,
						},
						["tilesize"] = 0,
						["texture"] = "ElvUI Blank",
					},
					["modeincombat"] = "",
					["classcolorbars"] = true,
					["isusingclasscolors"] = true,
					["showself"] = true,
					["classcolortext"] = false,
					["x"] = 0,
				}, -- [3]
			},
			["report"] = {
				["number"] = 8,
				["set"] = "total",
				["mode"] = "伤害",
				["channel"] = "guild",
			},
			["versions"] = {
				["1.6.7"] = true,
				["1.8.0"] = true,
				["1.6.4"] = true,
				["1.6.3"] = true,
			},
			["modeclicks"] = {
				["受到伤害"] = 1,
			},
		},
	},
}
